name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: fetch values from metadata.json
        run: |
          echo "VERSION=$(jq -r '.version' metadata.json)" >> $GITHUB_ENV
          echo "DESCRIPTION=$(jq -r '.description' metadata.json)" >> $GITHUB_ENV
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            DESCRIPTION=${{ env.DESCRIPTION }}
            COMMIT=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
